# @patriciogv - 2016

import:
    - ../blocks/source-terrarium.yaml
    - ../blocks/terrarium/lines.yaml
    - ../blocks/terrarium/polygons.yaml
    - ../blocks/terrarium/terrain.yaml
    - http://tangrams.github.io/blocks/filter/grid.yaml
    - http://tangrams.github.io/blocks/filter/height.yaml
    
cameras:
    default:
        type: perspective

scene:
    background: 
        color: black

lights:
    light:
        type: directional
        direction: [0.644,-0.552,-0.531]
        diffuse: .7
        ambient: .5

layers:
    terrain:
        data: { source: terrarium-geom }
        filter: { $zoom: { min: 15 } }
        draw:
            terrarium-terrain:
                order: 0
                color: white
    water:
        data: { source: osm, layer: water }
        draw:
            water:
                order: 1
                color: [0.1,0.1,0.1]
        continental_water:
            filter: { kind: [water, basin, reservoir, lake, canal, dam, ditch, drain, river, stream]}
            draw:
                terrarium_lines:
                    order: 2
                    color: [0.1,0.1,0.1]
                    width: 1px
    earth:
        data: { source: osm }
        flat:
            filter: { $zoom: { max: 15 } }
            draw:
                normals:
                    order: 0
                    color: white
        # elevated:
        #     filter: { $zoom: { min: 15 } }
        #     draw:
        #         terrarium_lns:
        #             order: 3
        #             color: white
        #             width: 2px

    roads:
        data: { source: osm}
        filter: { not: { kind: [rail, ferry] } }
        flat:
            filter: { $zoom: { max: 15 } }
            draw:
                lines:
                    order: 4
                    color: gray
                    width: [[7,0.0px], [10, .5px], [15, .75px]]
        elevated:
            filter: { $zoom: { min: 15 } }
            draw:
                roads:
                    order: 4
                    color: gray
                    width: [[15, .75px], [17, 5m]]
    buildings:
        data: { source: osm }
        flat:
            filter: { $zoom: { max: 15 } }
            draw:
                polygons:
                    order: 5
                    color: white
        elevated:
            filter: { $zoom: { min: 15 } }
            draw:
                buildings:
                    order: 5
                    color: white
                    extrude: true
styles:
    filter-height:
        shaders:
            blocks:
                color: |
                    color.rgb *= min((worldPosition().z*.0001 + .8), 1.);
    geometry-tilt:
        shaders:
            defines:
                TILT_IN: 14.
                TILT_OUT: 18.
    normals:
        base: polygons
        raster: normal
    ##################################################################  TERRARIUM STYLES
    terrarium_base:
        mix: [geometry-terrarium, geometry-tilt]
    terrarium_trn:
        base: polygons
        mix: [terrarium_base, filter-height]
        shaders:
            blocks:
                normal: |
                    normal = (sampleRaster(0).rgb-.5)*2.;
    terrarium_lns:
        base: lines
        mix: terrarium_base
        lighting: false
        shaders:
            defines:
                ZOFFSET: 1.
    ##################################################################  REGULAR STYLES
    water:
        base: polygons
        mix: [geometry-tilt, filter-grid]
    roads:
        base: lines
        mix: terrarium_base
    buildings:
        base: polygons
        mix: [terrarium_base, filter-height]